namespace java com.thrift.test

/* 维权状态*/
enum ComplainState {
	/* 1:等待折八百处理 */
	WAIT_ZHE800=1,
	/* 2:等待买家处理（待买家举证）-----废弃状态 */
	WAIT_BUYER=2,
	/* 3:等待卖家处理（待卖家举证）-----废弃状态 */
	WAIT_SELLER=3,
	/* 4:等待双方协商（双方协商解决） */
	WAIT_NEGO=4,
	/* 5:结方案等待审核（待审核） */
	WAIT_REVIEW=5,
}
