package lvsong.club.model.pojo;

import org.joda.time.DateTime;

public class Books {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author_name
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.create_time
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author_id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    private Integer authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author_name
     *
     * @return the value of books.author_name
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author_name
     *
     * @param authorName the value for books.author_name
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.create_time
     *
     * @return the value of books.create_time
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.create_time
     *
     * @param createTime the value for books.create_time
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author_id
     *
     * @return the value of books.author_id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author_id
     *
     * @param authorId the value for books.author_id
     *
     * @mbggenerated Fri May 13 21:33:14 CST 2016
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
}