/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thrift.test;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ComplainState implements org.apache.thrift.TEnum {
  WAIT_ZHE800(1),
  WAIT_BUYER(2),
  WAIT_SELLER(3),
  WAIT_NEGO(4),
  WAIT_REVIEW(5);

  private final int value;

  private ComplainState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ComplainState findByValue(int value) { 
    switch (value) {
      case 1:
        return WAIT_ZHE800;
      case 2:
        return WAIT_BUYER;
      case 3:
        return WAIT_SELLER;
      case 4:
        return WAIT_NEGO;
      case 5:
        return WAIT_REVIEW;
      default:
        return null;
    }
  }
}
